object Versions {
    const val room = "2.3.0"
    const val kotlin = "1.5.21"
    const val legacySupport = "1.0.0"
    const val coreKtx = "1.6.0"
    const val appCompat = "1.3.1"
    const val material = "1.4.0"
    const val constraintLayout = "2.1.1"
    const val swipeRefresh = "1.1.0"
    const val lifecycle = "2.3.1"
    const val threeTenABP = "1.3.1"
    const val viewBinding = "1.2.3"
    const val glide = "4.12.0"
    const val retrofitVersion = "2.6.4"
    const val rxJavaVersion = "2.2.17"
    const val rxAndroidVersion = "2.1.1"

    const val coreTesting = "2.1.0"
    const val mockk = "1.12.0"
    const val junit = "4.13.2"
    const val espresso = "3.1.0"
    const val androidXTest = "1.1.0"
    const val koin = "2.2.3"
    const val robolectric = "4.6.1"
    const val fragmentTesting = "1.3.1"
}